services:
  template-goose-db:
    container_name: template_goose_db
    image: mysql:9
    ports:
      - 20057:3306
    volumes:
      - "template-goose-db-data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=template_goose_db
    healthcheck:
      test: [ 'CMD', 'mysql', '-e', 'SHOW DATABASES;' ]
      interval: 5s
      timeout: 5s
      retries: 10

  template-goose-app:
    container_name: template_goose_app
    image: staleks/template-goose:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=int
      - DATABASE_HOST=template-goose-db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
    restart: on-failure
    depends_on:
      - template-goose-db

volumes:
  template-goose-db-data: