# starting -> docker-compose -f docker-compose.yaml -f docker-compose.app.yaml up -d
# stopping -> docker-compose -f docker-compose.yaml -f docker-compose.app.yaml down

services:
  template-goose-app:
    container_name: template_goose_app
    image: staleks/template-goose:latest
    network_mode: host
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: on-failure
    depends_on:
      - template-goose-db
